### ISSUE TITLE
[Bug] Name Not Disguised When User is Called Out With Radio Command "ttt_radio"

### ISSUE THREAD

**Issue by BDJslime-UnaverageJoe** [TTT-2/ttt2-wep_identity_disguiser#11]
See title, when someone uses an identity disguiser it still gets called out using their real name, even though their targetID and model is of the disguised target.
Major problem when used against people with ttt_radio binded, especially on the mouse as this effectively removes any effectiveness this item provides.

**Comment by TimGoll** [comment]
Good catch. I have to check this, I never used this command

**Comment by TimGoll** [comment]
We have to add a new hook to the base gamemode. It can therefore take a while. You have to wait for the next TTT2 update

**Comment by TimGoll** [comment]
fixed in dev, will be released soon
