### ISSUE TITLE
[Bug] Overhead icon is still shown if disguised

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/ttt2-wep_identity_disguiser#12]
If for example the Detective is disguised as a Traitor or as an Innocent then his Detective overhead icon will be still shown.
Here a picture: https://ibb.co/2jfvgVd

**Comment by TimGoll** [comment]
![image](https://user-images.githubusercontent.com/13639408/141807522-3dd39fc9-6ffd-469b-816b-d2d3ee3187ec.png)

Fixed in dev

**Comment by TimGoll** [comment]
Ref: https://github.com/TTT-2/TTT2/pull/924
